version: 2
sources:
  - name: supermarket
    schema: supermarket
    tables:
    - name: supermarket_branches
    - name: supermarket_categories
    - name: supermarket_customers
    - name: supermarket_locations
    - name: supermarket_products
    - name: supermarket_sales
